# Basic Settings
title: Priv360 • Leverage Privacy Investments • Grow your business
description: We optimize privacy compliance, building personal data security into the fabric of your organization, fostering consumer trust, fuelling growth and innovation.
author: dario
# Language format language_TERRITORY. Default is en_US
lang: en_US
# website logos, images & icons
logo: img/chklst.png
image: img/header.jpg
# urls
url: https://priv360.com
english_url: ''
french_url: 'fr'
baseurl: ''
resources_url: 'resources'
services_url: 'services'

# copyright text in footer
copyright: Priv360

# email address
email: contact@dario.com
email_username: contact@dario.com
# email address in privacy policy
email_privacy: privacy@dario.com

# contact telephone number
telephone_number:

# search tracking id for dario.best check before moving to .com
google_tracking_id: 

# verify check before moving to .com
webmaster_verifications:
  google: 
  bing: 
  alexa:
  yandex:
  baidu:

# Social/SEO
twitter_username: darioS3C
github_username:
facebook_username:

twitter:
  username: darioS3C

facebook:
  app_id:
  publisher:
  admins:

exclude: ["CNAME", "Gemfile", "Gemfile.lock", "NOTICE", "LICENSE", "README.md"]

# gems
gems:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
